name: Build and Test Project on Pull Request

on:
  pull_request:
    branches: [ "main", "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      - name: Install dependencies
        run: |
          ls
          pwd
          # npm install # or yarn install

      - name: Run tests 
        run: npm run test:ci